name: Deploy-Android-TEST
on:
  push:
    branches:    
      - 'main'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_BUR_ANDROID_TEST }}
  APP_NAME: ${{ 'burgueses-android/ENV_TEST' }}
  TESTING_GROUP: ${{ 'ENV_TEST' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04 # Works also with self hosted runner supporting docker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies 
        run: yarn

      - name: Build android
        run: cd android && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
